/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IImageDescriptor } from "./IImageDescriptor";
export type { MentorshipNFT } from "./MentorshipNFT";
export type { S1ImageDescriptor } from "./S1ImageDescriptor";
