/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IImageDescriptor,
  IImageDescriptorInterface,
} from "../../contracts/IImageDescriptor";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "image",
    outputs: [
      {
        internalType: "bool",
        name: "isRawSVG",
        type: "bool",
      },
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

export class IImageDescriptor__factory {
  static readonly abi = _abi;
  static createInterface(): IImageDescriptorInterface {
    return new Interface(_abi) as IImageDescriptorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IImageDescriptor {
    return new Contract(address, _abi, runner) as unknown as IImageDescriptor;
  }
}
